In [4]:
%pip install pandas numpy

Collecting pandas
  Using cached pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.5.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\HP\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\HP\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
Downloading numpy-2.5.4-cp314-cp314-win_amd64.whl (12.7 MB)
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.7 MB 731.7 kB/s eta 0:00:17
   - -------------------------------------- 0.5/12.7 MB 731.7 kB/s eta 0:00:17
   -- ------------------------------------- 0.8/12.7 MB 684.2 kB/s eta 0:00:18
   -- ------------------------------------- 0.8/12.7 MB 684.2 kB/s eta 0:00:18
   --- ------------------------------------ 1.0/12.7 MB 583.0 kB/s eta 0:00:20
   --- ------------------------------------ 1.0/12.7 MB 583.0 kB/s eta 0:00:20
   ---- ----------------------------------- 1.3/12.7 MB 613.7 kB/s eta 0:00:19
   ---- ----------------------------------- 1.3/12.7 MB 613.7 kB/s eta 0:00:19
   ---- ----------------------------------- 1.3/12.7 MB 613.7 kB/s eta 0:00:19
   ---- ----------------------------------- 1.3/12.7 MB 613.7 kB/s eta 0:00:19
   ---- ----------------------------------- 1.3/12.7 MB 613.7 kB/s eta 0:00:19
   ---- ----------------------------------- 1.3/12.7 MB 613.7 kB/s eta 0:00:19
   ---- ----------------------------------- 1.6/12.7 MB 448.9 kB/s eta 0:00:25
   ---- ----------------------------------- 1.6/12.7 MB 448.9 kB/s eta 0:00:25
   ----- ---------------------------------- 1.8/12.7 MB 479.7 kB/s eta 0:00:23
   ----- ---------------------------------- 1.8/12.7 MB 479.7 kB/s eta 0:00:23
   ----- ---------------------------------- 1.8/12.7 MB 479.7 kB/s eta 0:00:23
   ----- ---------------------------------- 1.8/12.7 MB 479.7 kB/s eta 0:00:23
   ----- ---------------------------------- 1.8/12.7 MB 479.7 kB/s eta 0:00:23
   ------ --------------------------------- 2.1/12.7 MB 428.3 kB/s eta 0:00:25
   ------ --------------------------------- 2.1/12.7 MB 428.3 kB/s eta 0:00:25
   ------- -------------------------------- 2.4/12.7 MB 429.2 kB/s eta 0:00:25
   ------- -------------------------------- 2.4/12.7 MB 429.2 kB/s eta 0:00:25
   ------- -------------------------------- 2.4/12.7 MB 429.2 kB/s eta 0:00:25
   ------- -------------------------------- 2.4/12.7 MB 429.2 kB/s eta 0:00:25
   --------- ------------------------------ 2.9/12.7 MB 471.4 kB/s eta 0:00:21
   --------- ------------------------------ 2.9/12.7 MB 471.4 kB/s eta 0:00:21
   --------- ------------------------------ 3.1/12.7 MB 472.3 kB/s eta 0:00:21
   --------- ------------------------------ 3.1/12.7 MB 472.3 kB/s eta 0:00:21
   ---------- ----------------------------- 3.4/12.7 MB 485.7 kB/s eta 0:00:20
   ---------- ----------------------------- 3.4/12.7 MB 485.7 kB/s eta 0:00:20
   ---------- ----------------------------- 3.4/12.7 MB 485.7 kB/s eta 0:00:20
   ----------- ---------------------------- 3.7/12.7 MB 483.7 kB/s eta 0:00:19
   ----------- ---------------------------- 3.7/12.7 MB 483.7 kB/s eta 0:00:19
   ------------ --------------------------- 3.9/12.7 MB 492.3 kB/s eta 0:00:18
   ------------- -------------------------- 4.2/12.7 MB 504.8 kB/s eta 0:00:17
   ------------- -------------------------- 4.2/12.7 MB 504.8 kB/s eta 0:00:17
   ------------- -------------------------- 4.2/12.7 MB 504.8 kB/s eta 0:00:17
   -------------- ------------------------- 4.5/12.7 MB 499.9 kB/s eta 0:00:17
   -------------- ------------------------- 4.5/12.7 MB 499.9 kB/s eta 0:00:17
   -------------- ------------------------- 4.7/12.7 MB 508.9 kB/s eta 0:00:16
   -------------- ------------------------- 4.7/12.7 MB 508.9 kB/s eta 0:00:16
   --------------- ------------------------ 5.0/12.7 MB 519.1 kB/s eta 0:00:15
   --------------- ------------------------ 5.0/12.7 MB 519.1 kB/s eta 0:00:15
   ---------------- ----------------------- 5.2/12.7 MB 517.1 kB/s eta 0:00:15
   ---------------- ----------------------- 5.2/12.7 MB 517.1 kB/s eta 0:00:15
   ----------------- ---------------------- 5.5/12.7 MB 523.9 kB/s eta 0:00:14
   ----------------- ---------------------- 5.5/12.7 MB 523.9 kB/s eta 0:00:14
   ----------------- ---------------------- 5.5/12.7 MB 523.9 kB/s eta 0:00:14
   ------------------ --------------------- 5.8/12.7 MB 517.5 kB/s eta 0:00:14
   ------------------ --------------------- 5.8/12.7 MB 517.5 kB/s eta 0:00:14
   ------------------ --------------------- 5.8/12.7 MB 517.5 kB/s eta 0:00:14
   ------------------- -------------------- 6.3/12.7 MB 533.1 kB/s eta 0:00:13
   ------------------- -------------------- 6.3/12.7 MB 533.1 kB/s eta 0:00:13
   ------------------- -------------------- 6.3/12.7 MB 533.1 kB/s eta 0:00:13
   -------------------- ------------------- 6.6/12.7 MB 529.8 kB/s eta 0:00:12
   -------------------- ------------------- 6.6/12.7 MB 529.8 kB/s eta 0:00:12
   -------------------- ------------------- 6.6/12.7 MB 529.8 kB/s eta 0:00:12
   --------------------- ------------------ 6.8/12.7 MB 524.9 kB/s eta 0:00:12
   --------------------- ------------------ 6.8/12.7 MB 524.9 kB/s eta 0:00:12
   ---------------------- ----------------- 7.1/12.7 MB 528.5 kB/s eta 0:00:11
   ---------------------- ----------------- 7.1/12.7 MB 528.5 kB/s eta 0:00:11
   ----------------------- ---------------- 7.3/12.7 MB 535.0 kB/s eta 0:00:11
   ----------------------- ---------------- 7.6/12.7 MB 541.0 kB/s eta 0:00:10
   ----------------------- ---------------- 7.6/12.7 MB 541.0 kB/s eta 0:00:10
   ----------------------- ---------------- 7.6/12.7 MB 541.0 kB/s eta 0:00:10
   ----------------------- ---------------- 7.6/12.7 MB 541.0 kB/s eta 0:00:10
   ----------------------- ---------------- 7.6/12.7 MB 541.0 kB/s eta 0:00:10
   ------------------------- -------------- 8.1/12.7 MB 541.9 kB/s eta 0:00:09
   ------------------------- -------------- 8.1/12.7 MB 541.9 kB/s eta 0:00:09
   -------------------------- ------------- 8.4/12.7 MB 538.8 kB/s eta 0:00:09
   -------------------------- ------------- 8.4/12.7 MB 538.8 kB/s eta 0:00:09
   --------------------------- ------------ 8.7/12.7 MB 542.8 kB/s eta 0:00:08
   --------------------------- ------------ 8.7/12.7 MB 542.8 kB/s eta 0:00:08
   --------------------------- ------------ 8.7/12.7 MB 542.8 kB/s eta 0:00:08
   --------------------------- ------------ 8.7/12.7 MB 542.8 kB/s eta 0:00:08
   ---------------------------- ----------- 8.9/12.7 MB 529.9 kB/s eta 0:00:08
   ---------------------------- ----------- 8.9/12.7 MB 529.9 kB/s eta 0:00:08
   ---------------------------- ----------- 9.2/12.7 MB 532.1 kB/s eta 0:00:07
   ---------------------------- ----------- 9.2/12.7 MB 532.1 kB/s eta 0:00:07
   ---------------------------- ----------- 9.2/12.7 MB 532.1 kB/s eta 0:00:07
   ----------------------------- ---------- 9.4/12.7 MB 528.3 kB/s eta 0:00:07
   ----------------------------- ---------- 9.4/12.7 MB 528.3 kB/s eta 0:00:07
   ----------------------------- ---------- 9.4/12.7 MB 528.3 kB/s eta 0:00:07
   ------------------------------ --------- 9.7/12.7 MB 524.7 kB/s eta 0:00:06
   ------------------------------ --------- 9.7/12.7 MB 524.7 kB/s eta 0:00:06
   ------------------------------ --------- 9.7/12.7 MB 524.7 kB/s eta 0:00:06
   ------------------------------- -------- 10.0/12.7 MB 521.5 kB/s eta 0:00:06
   ------------------------------- -------- 10.0/12.7 MB 521.5 kB/s eta 0:00:06
   -------------------------------- ------- 10.2/12.7 MB 524.2 kB/s eta 0:00:05
   -------------------------------- ------- 10.2/12.7 MB 524.2 kB/s eta 0:00:05
   -------------------------------- ------- 10.2/12.7 MB 524.2 kB/s eta 0:00:05
   -------------------------------- ------- 10.2/12.7 MB 524.2 kB/s eta 0:00:05
   --------------------------------- ------ 10.5/12.7 MB 514.3 kB/s eta 0:00:05
   --------------------------------- ------ 10.5/12.7 MB 514.3 kB/s eta 0:00:05
   --------------------------------- ------ 10.5/12.7 MB 514.3 kB/s eta 0:00:05
   --------------------------------- ------ 10.7/12.7 MB 512.0 kB/s eta 0:00:04
   --------------------------------- ------ 10.7/12.7 MB 512.0 kB/s eta 0:00:04
   ---------------------------------- ----- 11.0/12.7 MB 515.8 kB/s eta 0:00:04
   ---------------------------------- ----- 11.0/12.7 MB 515.8 kB/s eta 0:00:04
   ---------------------------------- ----- 11.0/12.7 MB 515.8 kB/s eta 0:00:04
   ----------------------------------- ---- 11.3/12.7 MB 511.3 kB/s eta 0:00:03
   ----------------------------------- ---- 11.3/12.7 MB 511.3 kB/s eta 0:00:03
   ----------------------------------- ---- 11.3/12.7 MB 511.3 kB/s eta 0:00:03
   ------------------------------------ --- 11.5/12.7 MB 508.3 kB/s eta 0:00:03
   ------------------------------------ --- 11.5/12.7 MB 508.3 kB/s eta 0:00:03
   ------------------------------------ --- 11.5/12.7 MB 508.3 kB/s eta 0:00:03
   ------------------------------------- -- 11.8/12.7 MB 506.9 kB/s eta 0:00:02
   ------------------------------------- -- 11.8/12.7 MB 506.9 kB/s eta 0:00:02
   ------------------------------------- -- 11.8/12.7 MB 506.9 kB/s eta 0:00:02
   ------------------------------------- -- 12.1/12.7 MB 503.9 kB/s eta 0:00:02
   ------------------------------------- -- 12.1/12.7 MB 503.9 kB/s eta 0:00:02
   ------------------------------------- -- 12.1/12.7 MB 503.9 kB/s eta 0:00:02
   -------------------------------------- - 12.3/12.7 MB 501.7 kB/s eta 0:00:01
   -------------------------------------- - 12.3/12.7 MB 501.7 kB/s eta 0:00:01
   -------------------------------------- - 12.3/12.7 MB 501.7 kB/s eta 0:00:01
   ---------------------------------------  12.6/12.7 MB 500.0 kB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 502.8 kB/s  0:00:25
Downloading tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\HP\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.6
NumPy version: 2.5.4

In [6]:
import pandas as pd

players = {
    "Player": ["Adeyemi", "Okafor", "Balogun"],
    "Position": ["CM", "LW", "CB"],
    "Distance_km": [10.8, 11.2, 8.7]
}

df = pd.DataFrame(players)

df

    Player Position  Distance_km
0  Adeyemi       CM         10.8
1   Okafor       LW         11.2
2  Balogun       CB          8.7

In [7]:
import pandas as pd
import numpy as np

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("players.csv")
df

,player_id,name,position,age,team,games_played,minutes,points,assists,personal_fouls,technical_fouls
0,1,Adeyemi,PG,24,Lagos Leopards,28,896,336,196,58,0
1,2,Okafor,SG,29,Lagos Leopards,30,960,540,120,64,1
2,3,Balogun,SF,26,Lagos Leopards,27,864,410,140,70,0
3,4,Diallo,PF,31,Lagos Leopards,29,928,380,60,112,2
4,5,Nwosu,C,28,Lagos Leopards,30,900,340,40,128,1
5,6,Owusu,PG,22,Accra Aces,25,700,245,175,45,0
6,7,Appiah,SG,27,Accra Aces,28,868,460,90,58,0
7,8,Danquah,SF,25,Accra Aces,26,780,360,110,66,0
8,9,Bello,PF,30,Accra Aces,29,870,330,55,118,3
9,10,Chukwu,C,33,Accra Aces,27,756,260,35,130,1
10,11,Eneh,PG,23,Kano Kings,24,672,230,168,42,0
11,12,Gyamfi,SG,26,Kano Kings,29,870,470,95,60,0
12,13,Hassan,SF,28,Kano Kings,30,930,420,120,74,1
13,14,Ikpeba,PF,24,Kano Kings,22,660,255,48,95,2
14,15,Jalloh,C,31,Kano Kings,28,812,290,30,120,2
15,16,Kamara,PG,20,Abuja Pythons,18,486,160,120,30,0
16,17,Lawal,SG,25,Abuja Pythons,27,810,430,80,52,0
17,18,Mohammed,SF,29,Abuja Pythons,29,870,395,105,68,0
18,19,Nkrumah,PF,27,Abuja Pythons,26,780,300,50,105,1
19,20,Oduya,C,32,Abuja Pythons,30,870,315,32,132,1
20,21,Peprah,PG,26,Kumasi Giants,19,342,120,90,22,0
21,22,Quansah,SG,21,Kumasi Giants,15,240,120,30,16,0
22,23,Rahman,SF,33,Kumasi Giants,11,154,60,18,14,0
23,24,Sowah,PF,28,Kumasi Giants,22,374,150,25,55,0
24,25,Tetteh,C,30,Kumasi Giants,24,384,140,15,60,1

Exploratory Analysis

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   player_id        25 non-null     int64
 1   name             25 non-null     str
 2   position         25 non-null     str
 3   age              25 non-null     int64
 4   team             25 non-null     str
 5   games_played     25 non-null     int64
 6   minutes          25 non-null     int64
 7   points           25 non-null     int64
 8   assists          25 non-null     int64
 9   personal_fouls   25 non-null     int64
 10  technical_fouls  25 non-null     int64
dtypes: int64(8), str(3)
memory usage: 2.3 KB

In [12]:
df.describe()

,player_id,age,games_played,minutes,points,assists,personal_fouls,technical_fouls
count,25.000000,25.000000,25.000000,25.000000,25.000000,25.00000,25.000000,25.000000
mean,13.000000,27.120000,25.320000,711.040000,300.640000,81.88000,71.760000,0.640000
std,7.359801,3.609247,5.014313,237.288938,125.877877,52.22493,36.298852,0.860233
min,1.000000,20.000000,11.000000,154.000000,60.000000,15.00000,14.000000,0.000000
25%,7.000000,25.000000,24.000000,660.000000,230.000000,35.00000,52.000000,0.000000
50%,13.000000,27.000000,27.000000,810.000000,315.000000,80.00000,64.000000,0.000000
75%,19.000000,30.000000,29.000000,870.000000,395.000000,120.00000,105.000000,1.000000
max,25.000000,33.000000,30.000000,960.000000,540.000000,196.00000,132.000000,3.000000

In [13]:
print (df.columns)

Index(['player_id', 'name', 'position', 'age', 'team', 'games_played',
       'minutes', 'points', 'assists', 'personal_fouls', 'technical_fouls'],
      dtype='str')

In [14]:
print (df.iloc[0])

player_id                       1
name                      Adeyemi
position                       PG
age                            24
team               Lagos Leopards
games_played                   28
minutes                       896
points                        336
assists                       196
personal_fouls                 58
technical_fouls                 0
Name: 0, dtype: object

In [20]:
print

,player_id,name,position,age,team,games_played,minutes,points,assists,personal_fouls,technical_fouls
8,9,Bello,PF,30,Accra Aces,29,870,330,55,118,3

In [21]:
del print

In [22]:
print(df.loc[df['name'] == 'Bello'])

   player_id   name position  age        team  games_played  minutes  points  \
8          9  Bello       PF   30  Accra Aces            29      870     330

   assists  personal_fouls  technical_fouls
8       55             118                3

In [1]:
print(df.loc[df['team'] == 'Accra Aces'])

NameError: name 'df' is not defined

In [2]:
import pandas as pd

df = pd.read_csv("players.csv")

In [3]:
print(df.loc[df['team'] == 'Accra Aces'])

   player_id     name position  age        team  games_played  minutes  \
5          6    Owusu       PG   22  Accra Aces            25      700
6          7   Appiah       SG   27  Accra Aces            28      868
7          8  Danquah       SF   25  Accra Aces            26      780
8          9    Bello       PF   30  Accra Aces            29      870
9         10   Chukwu        C   33  Accra Aces            27      756

   points  assists  personal_fouls  technical_fouls
5     245      175              45                0
6     460       90              58                0
7     360      110              66                0
8     330       55             118                3
9     260       35             130                1

In [4]:
guards = df[df["position"].isin(["SG", "PG"])]
print(guards.shape)
print(guards.head(5))

(10, 11)
    player_id     name position  age            team  games_played  minutes  \
0           1  Adeyemi       PG   24  Lagos Leopards            28      896
1           2   Okafor       SG   29  Lagos Leopards            30      960
5           6    Owusu       PG   22      Accra Aces            25      700
6           7   Appiah       SG   27      Accra Aces            28      868
10         11     Eneh       PG   23      Kano Kings            24      672

    points  assists  personal_fouls  technical_fouls
0      336      196              58                0
1      540      120              64                1
5      245      175              45                0
6      460       90              58                0
10     230      168              42                0

In [5]:

df["points_plus_assists"] = df["points"] + df["assists"]

df["points_per_36"] = df["points"] / (df["minutes"] / 36)

df["minutes_per_game"] = df["minutes"] / df["games_played"]

df.head()

,player_id,name,position,age,team,games_played,minutes,points,assists,personal_fouls,technical_fouls,points_plus_assists,points_per_36,minutes_per_game
0,1,Adeyemi,PG,24,Lagos Leopards,28,896,336,196,58,0,532,13.500000,32.0
1,2,Okafor,SG,29,Lagos Leopards,30,960,540,120,64,1,660,20.250000,32.0
2,3,Balogun,SF,26,Lagos Leopards,27,864,410,140,70,0,550,17.083333,32.0
3,4,Diallo,PF,31,Lagos Leopards,29,928,380,60,112,2,440,14.741379,32.0
4,5,Nwosu,C,28,Lagos Leopards,30,900,340,40,128,1,380,13.600000,30.0

In [6]:
guards = df[df["position"].isin(["SG", "PG" "PF"])]
print(guards.shape)
print(guards.head(5))

(5, 14)
    player_id     name position  age            team  games_played  minutes  \
1           2   Okafor       SG   29  Lagos Leopards            30      960
6           7   Appiah       SG   27      Accra Aces            28      868
11         12   Gyamfi       SG   26      Kano Kings            29      870
16         17    Lawal       SG   25   Abuja Pythons            27      810
21         22  Quansah       SG   21   Kumasi Giants            15      240

    points  assists  personal_fouls  technical_fouls  points_plus_assists  \
1      540      120              64                1                  660
6      460       90              58                0                  550
11     470       95              60                0                  565
16     430       80              52                0                  510
21     120       30              16                0                  150

    points_per_36  minutes_per_game
1       20.250000              32.0
6       19.078341              31.0
11      19.448276              30.0
16      19.111111              30.0
21      18.000000              16.0

In [7]:
df.to_csv("players_updated.csv", index=False)